//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWI.SoftStock.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateUserStatus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateUserStatus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWI.SoftStock.WebApi.Resources.CreateUserStatus", typeof(CreateUserStatus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact us.
        /// </summary>
        internal static string CreateUserStatus_Default {
            get {
                return ResourceManager.GetString("CreateUserStatus_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name already exists. Please enter a different company name.
        /// </summary>
        internal static string CreateUserStatus_DuplicateCompany {
            get {
                return ResourceManager.GetString("CreateUserStatus_DuplicateCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user name for that e-mail address already exists. Please enter a different e-mail address.
        /// </summary>
        internal static string CreateUserStatus_DuplicateEmail {
            get {
                return ResourceManager.GetString("CreateUserStatus_DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists. Please enter a different user name.
        /// </summary>
        internal static string CreateUserStatus_DuplicateUserName {
            get {
                return ResourceManager.GetString("CreateUserStatus_DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again.
        /// </summary>
        internal static string CreateUserStatus_InvalidAnswer {
            get {
                return ResourceManager.GetString("CreateUserStatus_InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is invalid. Please check the value and try again.
        /// </summary>
        internal static string CreateUserStatus_InvalidEmail {
            get {
                return ResourceManager.GetString("CreateUserStatus_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value.
        /// </summary>
        internal static string CreateUserStatus_InvalidPassword {
            get {
                return ResourceManager.GetString("CreateUserStatus_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again.
        /// </summary>
        internal static string CreateUserStatus_InvalidQuestion {
            get {
                return ResourceManager.GetString("CreateUserStatus_InvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again.
        /// </summary>
        internal static string CreateUserStatus_InvalidUserName {
            get {
                return ResourceManager.GetString("CreateUserStatus_InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact us.
        /// </summary>
        internal static string CreateUserStatus_ProviderError {
            get {
                return ResourceManager.GetString("CreateUserStatus_ProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact us.
        /// </summary>
        internal static string CreateUserStatus_UserRejected {
            get {
                return ResourceManager.GetString("CreateUserStatus_UserRejected", resourceCulture);
            }
        }
    }
}
